services:
  - type: web
    name: my-portofolio-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_FLYWAY_ENABLED
        value: "true"
      - key: APP_FRONTEND_ORIGIN
        value: https://efatha.github.io
