services:
  - type: web
    name: my-portofolio-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-sparkling-sunset-ayo4o7ls-pooler.c-5.us-east-2.aws.neon.tech/my_portofolio_db?sslmode=require&channel_binding=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_FLYWAY_ENABLED
        value: "true"
      - key: APP_FRONTEND_ORIGIN
        value: https://efatha.github.io
